<?php

namespace Pichet\CoreBundle\Repository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllInfoEntreprise(){
        $query = $this->createQueryBuilder('p')
            ->select('COUNT(p)')
        ;
        return $query
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }

    public function getAllEntreprise(){
        $query = $this->createQueryBuilder('p')
        ->select('COUNT(p), p.service')
        ->groupBy('p.service')
        ;
        return $query
            ->getQuery()
            ->getResult()
            ;
    }
}
