pichet_core_step:
    path:     /step/{step}
    defaults:
        _controller: PichetCoreBundle:User:form
        title:       "Hello world!"


pichet_core_homepage:
    path:     /accueilAdmin
    defaults: { _controller: PichetCoreBundle:Admin:home }

pichet_core_admin_ajax_add_participe:
    path:     /participe/add
    defaults: { _controller: PichetCoreBundle:Ajax:addClickParticiper }

pichet_core_tracking:
    path:     /track.gif
    defaults: { _controller: PichetCoreBundle:Ajax:addOpenMail }


